<a href="https://colab.research.google.com/github/Harish67010/NEURAL/blob/main/Week%202%20%20700756701_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a class Employee and then do the following:                                     



• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Harish goud", "Matta", 150000, "Manager")
employee2 = Employee("Nagarjun", "Boddupalli", 80000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Ram", "Palreddy", 85000, "Finance")
fulltime_employee2 = FulltimeEmployee("Sravan Kumar", "Jajam", 70000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)



Average Salary for Employees: 57500.0
Average Salary for Fulltime Employees: 38750.0


2.Numpy


Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)


In [2]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 2.28408478 16.00130196  9.8580672   5.61146998 15.24953826  2.16666259
  6.46913898  6.4690075   5.08855948 13.36124761  3.62741046 11.93642759
 11.43348227 17.70288565 17.91411101 15.00328624  8.21797579  8.76009732
  5.7242566   6.35869096]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 2.28408478 16.00130196  9.8580672   5.61146998 15.24953826]
 [ 2.16666259  6.46913898  6.4690075   5.08855948 13.36124761]
 [ 3.62741046 11.93642759 11.43348227 17.70288565 17.91411101]
 [15.00328624  8.21797579  8.76009732  5.7242566   6.35869096]]


In [4]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 2.28408478  0.          9.8580672   5.61146998 15.24953826]
 [ 2.16666259  6.46913898  6.4690075   5.08855948  0.        ]
 [ 3.62741046 11.93642759 11.43348227 17.70288565  0.        ]
 [ 0.          8.21797579  8.76009732  5.7242566   6.35869096]]
